[servers]
rif-u22-ger ansible_host=89.125.60.36 
priboi-u22-ru ansible_host=212.15.49.66 
vova-u22-ru ansible_host=81.29.146.124
vova-u22-ger ansible_host=194.87.54.34
vova-u22-us ansible_host=192.177.26.107
#ostrov via headscale on rif
ostrov ansible_host=100.64.0.4


# ostrov via reverse ssh on priboi
[ostrov]
ostrov-u24 ansible_host=127.0.0.1 ansible_port=3333
# ostrov_lxc via reverse ssh on priboi
[ostrov_lxc]
awg-lxc ansible_host=127.0.0.1 ansible_port=3334
headscale-lxc ansible_host=127.0.0.1 ansible_port=3335

[bootstrap]

[openclaw]
#rif-u22-ger ansible_host=89.125.60.36 
vova-u22 ansible_host=81.29.146.124
