- name: Setup and configure fail2ban on Ubuntu 22
  hosts: servers
  gather_facts: true
  become: true

  tasks:
    - name: Install fail2ban
      ansible.builtin.apt:
        name: fail2ban
        state: present
        update_cache: true

    - name: Ensure fail2ban is enabled and started
      ansible.builtin.service:
        name: fail2ban
        enabled: true
        state: started

    - name: Check if cockpit is installed
      ansible.builtin.systemd:
        name: cockpit.socket
      register: cockpit_service
      failed_when: false
      changed_when: false

    - name: Create cockpit fail2ban filter
      ansible.builtin.copy:
        dest: /etc/fail2ban/filter.d/cockpit.conf
        content: |
          [Definition]
          failregex = ^.*cockpit-ws\[[0-9]+\]: .* Login failed for .*from <HOST>.*$
                      ^.*cockpit-session\[[0-9]+\]: pam_unix\(cockpit:auth\): authentication failure; .* rhost=<HOST>.*$
                      ^.*cockpit-session\[[0-9]+\]: pam_succeed_if\(cockpit:auth\): requirement .* not met by user .*\(authenticated from <HOST>\)$
          ignoreregex =
        owner: root
        group: root
        mode: '0644'
      notify: Restart fail2ban
      when: cockpit_service.status is defined and cockpit_service.status.LoadState == "loaded"

    - name: Create jail.local configuration (with cockpit)
      ansible.builtin.copy:
        dest: /etc/fail2ban/jail.local
        content: |
          [DEFAULT]
          # Основные параметры блокировки
          bantime = 1h
          findtime = 15m
          maxretry = 5
          
          # Игнорируемые IP (локальные сети)
          ignoreip = 127.0.0.1/8 ::1
          
          # Отключаем email уведомления
          destemail = root@localhost
          sender = fail2ban@localhost
          action = %(action_)s
          
          # Backend для мониторинга логов
          backend = systemd
          
          [sshd]
          enabled = true
          port = ssh
          logpath = %(sshd_log)s
          backend = %(sshd_backend)s
          
          [cockpit]
          enabled = true
          port = 9090
          filter = cockpit
          backend = systemd
          maxretry = 10
          findtime = 15m
          bantime = 1h
          
          [recidive]
          enabled = true
          filter = recidive
          logpath = /var/log/fail2ban.log
          action = %(action_)s
          protocol = all
          # Бан на 7 дней для рецидивистов
          bantime = 7d
          # 3 бана за 1 день = долгий бан
          findtime = 1d
          maxretry = 3
          
          [cockpit-recidive]
          enabled = true
          filter = recidive
          logpath = /var/log/fail2ban.log
          action = %(action_)s
          protocol = all
          # Перманентный бан для рецидивистов Cockpit
          bantime = -1
          # 5 банов = перманентный бан
          findtime = 365d
          maxretry = 5
        owner: root
        group: root
        mode: '0644'
      notify: Restart fail2ban
      when: cockpit_service.status is defined and cockpit_service.status.LoadState == "loaded"

    - name: Create jail.local configuration (without cockpit)
      ansible.builtin.copy:
        dest: /etc/fail2ban/jail.local
        content: |
          [DEFAULT]
          # Основные параметры блокировки
          bantime = 1h
          findtime = 15m
          maxretry = 5
          
          # Игнорируемые IP (локальные сети)
          ignoreip = 127.0.0.1/8 ::1
          
          # Отключаем email уведомления
          destemail = root@localhost
          sender = fail2ban@localhost
          action = %(action_)s
          
          # Backend для мониторинга логов
          backend = systemd
          
          [sshd]
          enabled = true
          port = ssh
          logpath = %(sshd_log)s
          backend = %(sshd_backend)s
          
          [recidive]
          enabled = true
          filter = recidive
          logpath = /var/log/fail2ban.log
          action = %(action_)s
          protocol = all
          # Бан на 7 дней для рецидивистов
          bantime = 7d
          # 3 бана за 1 день = долгий бан
          findtime = 1d
          maxretry = 3
        owner: root
        group: root
        mode: '0644'
      notify: Restart fail2ban
      when: cockpit_service.status is not defined or cockpit_service.status.LoadState != "loaded"

    - name: Verify fail2ban configuration
      ansible.builtin.command: fail2ban-client -t
      register: fail2ban_test
      changed_when: false
      failed_when: fail2ban_test.rc != 0

    - name: Get fail2ban status
      ansible.builtin.command: fail2ban-client status
      register: fail2ban_status
      changed_when: false

    - name: Print fail2ban status
      ansible.builtin.debug:
        msg: "{{ fail2ban_status.stdout_lines }}"

  handlers:
    - name: Restart fail2ban
      ansible.builtin.service:
        name: fail2ban
        state: restarted