#!/usr/bin/env python3
"""Import an AmneziaWG config file into group_vars for the ostrov playbook."""

from __future__ import annotations

import argparse
import configparser
import re
from pathlib import Path


AWG_KEYS = (
    "Jc",
    "Jmin",
    "Jmax",
    "S1",
    "S2",
    "S3",
    "S4",
    "H1",
    "H2",
    "H3",
    "H4",
    "I1",
    "I2",
    "I3",
    "I4",
    "I5",
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Import AWG client config into group_vars/ostrov.yml"
    )
    parser.add_argument("config", type=Path, help="Path to source AWG config")
    parser.add_argument(
        "--dest",
        type=Path,
        default=Path("group_vars/ostrov.yml"),
        help="Path to destination group_vars file",
    )
    parser.add_argument(
        "--interface",
        default="awg0",
        help="Interface name for the generated playbook variables",
    )
    parser.add_argument(
        "--routes",
        nargs="*",
        help="Explicit route CIDRs. Defaults to AllowedIPs from the imported config.",
    )
    parser.add_argument(
        "--mtu",
        type=int,
        help="Optional awg_mtu override",
    )
    parser.add_argument(
        "--keepalive",
        type=int,
        help="Optional awg_persistent_keepalive override",
    )
    return parser.parse_args()


def split_csv(value: str | None) -> list[str]:
    if not value:
        return []
    return [item.strip() for item in value.split(",") if item.strip()]


def yaml_quote(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def yaml_list(items: list[str], indent: int = 0) -> list[str]:
    pad = " " * indent
    return [f"{pad}- {item}" for item in items]


def build_awg_block(
    interface: str,
    interface_cfg: configparser.SectionProxy,
    peer_cfg: configparser.SectionProxy,
    routes_override: list[str] | None,
    mtu_override: int | None,
    keepalive_override: int | None,
) -> str:
    addresses = split_csv(interface_cfg.get("Address"))
    allowed_ips = split_csv(peer_cfg.get("AllowedIPs"))

    endpoint = peer_cfg.get("Endpoint", "")
    if ":" not in endpoint:
        raise ValueError(f"Endpoint must be in host:port form, got: {endpoint!r}")
    endpoint_host, endpoint_port = endpoint.rsplit(":", 1)

    routes = routes_override if routes_override else allowed_ips

    lines: list[str] = [
        "# AmneziaWG client settings for ostrov.",
        "# Generated by scripts/import-awg-config.py",
        f"awg_interface: {interface}",
        "awg_client_addresses:",
        *yaml_list(addresses, indent=2),
        "awg_allowed_ips:",
        *yaml_list(allowed_ips, indent=2),
        "awg_route_cidrs:",
        *yaml_list(routes, indent=2),
        f"awg_endpoint_host: {endpoint_host}",
        f"awg_endpoint_port: {endpoint_port}",
        f"awg_private_key: {yaml_quote(interface_cfg['PrivateKey'])}",
        f"awg_server_public_key: {yaml_quote(peer_cfg['PublicKey'])}",
    ]

    preshared_key = peer_cfg.get("PresharedKey")
    if preshared_key:
        lines.append(f"awg_preshared_key: {yaml_quote(preshared_key)}")

    dns = split_csv(interface_cfg.get("DNS"))
    if dns:
        lines.append("awg_dns:")
        lines.extend(yaml_list(dns, indent=2))

    keepalive = (
        keepalive_override
        if keepalive_override is not None
        else peer_cfg.get("PersistentKeepalive")
    )
    if keepalive not in (None, ""):
        lines.append(f"awg_persistent_keepalive: {keepalive}")

    mtu = mtu_override if mtu_override is not None else interface_cfg.get("MTU")
    if mtu not in (None, ""):
        lines.append(f"awg_mtu: {mtu}")

    for key in AWG_KEYS:
        value = interface_cfg.get(key)
        if value not in (None, ""):
            lines.append(f"awg_{key.lower()}: {yaml_quote(value)}")

    return "\n".join(lines) + "\n"


def replace_awg_block(content: str, awg_block: str) -> str:
    marker = "# AmneziaWG client settings for ostrov."
    if marker not in content:
        if content and not content.endswith("\n"):
            content += "\n"
        return content + "\n" + awg_block

    pattern = re.compile(r"(?ms)^# AmneziaWG client settings for ostrov\.\n.*\Z")
    return pattern.sub(awg_block, content)


def main() -> int:
    args = parse_args()

    parser = configparser.ConfigParser(interpolation=None)
    parser.optionxform = str
    with args.config.open("r", encoding="utf-8") as handle:
        parser.read_file(handle)

    if "Interface" not in parser or "Peer" not in parser:
        raise ValueError("Config must contain [Interface] and [Peer] sections")

    awg_block = build_awg_block(
        interface=args.interface,
        interface_cfg=parser["Interface"],
        peer_cfg=parser["Peer"],
        routes_override=args.routes,
        mtu_override=args.mtu,
        keepalive_override=args.keepalive,
    )

    existing = args.dest.read_text(encoding="utf-8") if args.dest.exists() else ""
    updated = replace_awg_block(existing, awg_block)
    args.dest.write_text(updated, encoding="utf-8")

    print(f"Imported {args.config} into {args.dest}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
